[package]
name = "genact"
description = "A nonsense activity generator"
version = "0.7.0"
repository = "https://github.com/svenstaro/genact"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["fake", "nonsense", "useless"]
categories = ["command-line-utilities", "command-line-interface"]
edition = "2018"

[badges]
travis-ci = { repository = "svenstaro/genact", branch = "master" }
maintenance = { status = "actively-developed" }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'

[dependencies]
pbr = "1.0"
yansi = "0.5"
rand = "0.7.0"
rand_distr = "0.2.1"
chrono = "0.4"
url = "2.1"
lazy_static = "1.4"
humantime = "1.1"
regex = "1.3"
fake = { git = "https://github.com/svenstaro/fake-rs.git", branch = "patch-2" }

[target.'cfg(not(target_os = "emscripten"))'.dependencies]
clap = "2.29"
ctrlc = "3.1"

[target.'cfg(target_os = "emscripten")'.dependencies]
stdweb = { git = "https://github.com/koute/stdweb.git", features = ["experimental_features_which_may_break_on_minor_version_bumps"] }

[profile.dev]
debug = 1  # Required due to emscripten with emterpretify
